# Dockerfile for Terminal Trail
# Works with AWS App Runner and local Docker

FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements first (for better caching)
COPY requirements-web.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements-web.txt

# Copy game files
COPY *.py ./
COPY challenges/ ./challenges/
COPY assets/ ./assets/

# Note: web_static/ is auto-generated by web_server.py on first run

# Create directory for progress files
RUN mkdir -p /app/data

# Expose port (AWS App Runner uses 8000 by default)
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"

# Run the server
# AWS App Runner will use this CMD
CMD ["uvicorn", "web_server:app", "--host", "0.0.0.0", "--port", "8000"]
